### ISSUE TITLE
Podman Desktop SSH Tunnel

### ISSUE THREAD

**Issue by PinoOG** [containers/podman-desktop#2898] opened 2023-06-17 08:33 UTC
### Is your feature request related to a problem? Please describe

Hello,

would be cool with podman desktop to have an option to connect with the UI of podman desktop to a podman container using SSH Tunnell or connecting directly via IP.

### Describe the solution you'd like

For example, I have an SSH Tunnell binding towards the port of a podman container on my server (127.0.0.1:3345)
With Podman Desktop adding the container using 127.0.0.1:3345 and connecting, stopping or attaching to him.

**Comment by benoitf** [comment] 2023-06-19 14:16
closing as a duplicate of https://github.com/containers/podman-desktop/issues/279

**Closed as not planned by benoitf** 2023-06-19 14:16 UTC
