### ISSUE TITLE
Podman Desktop x.xx Released updater wrongly appearing

### ISSUE THREAD

**Issue by ylluminate** [containers/podman-desktop#9521] opened 2024-10-22 07:20 UTC
### UX Description

After installing Podman Desktop via Homebrew on macOS I've noticed that an update prompt appears wrongly when no other version actually appears to be visible:
![image](https://p153.p0.n0.cdn.zight.com/items/7KuNnxPY/97f084e0-ab28-46b2-956c-731f80c123af.png?v=545f219e3413de9582f8dc1863e16f76)

Most recent Release available:
![image](https://p153.p0.n0.cdn.zight.com/items/NQu9Be9X/7ea5c4de-b945-41d5-aee8-35e8c7e20378.png?v=188da6bca6e2b40b2ee6a526b3f2a8ba)

What pressing "Update" button shows:
![image](https://p153.p0.n0.cdn.zight.com/items/GGued09z/f0603eef-b34d-4edb-bb8f-f9117475673a.png?v=5157ad7e512a303ef3c9f26eb8c7932e)

If I try the update, which I shouldn't (need to do), it yields:
![image](https://p153.p0.n0.cdn.zight.com/items/Kou8KQXY/91088303-bd34-4e9a-aa2f-e22bd8eea5d6.png?v=2e22109c75e810b83c1f351c669e232a)

Obviously this should not be happening.

### Request type

UX analysis/suggestions for improvement

**Comment by odockal** [comment] 2024-10-23 18:47
I think this is a dupe of https://github.com/containers/podman-desktop/issues/9365. Should be fixed soon.

**Comment by odockal** [comment] 2024-10-24 15:00
1.13.3 still contains the problem:
![Image](https://github.com/user-attachments/assets/41bac0d1-b8b4-42ed-bec7-5c73ca8b059d)

**Closed as completed** 2024-10-28 11:27 UTC
Labels: sprint/unplanned, area/update, UX/UI Issue
