### ISSUE TITLE
Ports not created after importing Kubernetes YAML

### ISSUE THREAD

**Issue by milutinKY** [containers/podman-desktop#712] opened 2022-10-27 10:33 UTC
### Bug description

After uploading YAML file Images are pulled and pod with containers are created, but no ports were opened.

### Operating system

Windows 10 Wnterprise

### Version

0.9.0

### Steps to reproduce

Start new clean machine. (optional)

Go to "Containers" tab then
Click on "Play Kubernetes YAML"
Upload file.
[itrix_gh.yaml.txt](https://github.com/containers/podman-desktop/files/9878389/itrix_gh.yaml.txt)

Expected result 1:
- When I go to Containers
- Open one container
- Go to "Details" tab
- "Ports" Should list ports instead of N/A

Expected result 2:
- Pod should have open ports 80 and 443

**Comment by benoitf** [comment] 2022-10-27 11:56
@milutinKY yes I agree. The problem is that podman engine is not yet providing these metadata on the created pod.

**Comment by benoitf** [comment] 2022-10-27 19:55
Related to https://github.com/containers/podman-desktop/issues/542

**Comment by lstocchi** [comment] 2023-01-31 13:52
@benoitf i guess this has been fixed. I see the ports correctly displayed. Maybe we should remove the "PORTS:" string
![immagine](https://user-images.githubusercontent.com/49404737/215778625-3ecf17aa-1f90-48d4-9bd5-2533d0aceb4b.png)

**Comment by benoitf** [comment] 2023-01-31 14:03
@lstocchi thanks for checking. Yes it looks it has been fixed now from podman side and yes to your suggestion (avoid duplicated `PORTS:`).

**Closed as completed** 2023-02-19 05:26 UTC
Labels: area/podman-upstream 🦭
