### ISSUE TITLE
Kubernetes Suite 2: On Windows, the container built from podman-desktop-demo/primary-podify-demo/front/ does not start

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2412] opened 2023-05-09 14:55 UTC
### Bug description

On Windows, the container built from podman-desktop-demo/primary-podify-demo/front/ does not start.

### Operating system

Windows 10 Professional

### Version

next (development version)

### Steps to reproduce

1. Git clone https://github.com/redhat-developer/podman-desktop-demo 
2. Images > Pull an image: quay.io/centos7/redis-5-centos7
3. Images > quay.io/centos7/redis-5-centos7 > Start: Container name: enter redis 
4. Using inspect tag, get the IP address for the container (NetworkSettings.IPAddress)
5. Build an image:
	1. Containerfile path:  podman-desktop-demo/primary-podify-demo/front/Dockerfile 
	2. Image name: my-python-app:1.0
3. History: Verify the `entrypoint.sh` has been added to the image:

   ```
   /bin/sh -c #(nop) ENTRYPOINT ["/entrypoint.sh"]
   /bin/sh -c chmod +x /entrypoint.sh
   /bin/sh -c #(nop) COPY file:c13f1a65ff5b4bc83a7c43a0d99cf1c014a45fcc15380018494e7ab1e76a3a77 in / 
   ```

8. Start my-python-app:1.0
	1. Basic: mapping port 5000 to local port 5000 
	2. Networking: Add extra hosts:  redis to the IP retrieved in previous step
1. The container fails to start with the error: 

   ```
   {"msg":"exec container process (missing dynamic library?) `/entrypoint.sh`: No such file or directory","level":"error","time":"2023-05-09T14:45:55.582751Z"}
   ```

### Additional context

On Linux, the container built from the same source starts.

**Comment by jeffmaury** [comment] 2023-06-01 15:49
Cannot reproduce thus closing

**Closed as completed by jeffmaury** 2023-06-01 15:49 UTC
