### ISSUE TITLE
Compose does not work with a rootless podman machine on windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3560] opened 2023-08-16 15:46 UTC
### Bug description

I am trying to use a compose installed through a Podman Desktop to spin up flask compose example [1]. I am also having a default podman machine installed on laptop via podman desktop. This machine is rootless. On a cli, I run `docker-compose.exe up -d` in a flask folder and get: `Error response from daemon: crun: creating cgroup directory `/sys/fs/cgroup/misc/docker/buildx/libpod-e8e918dd83ea5605e3b70e5c37ccd65262eb0534377fb56d8ca29d02058f3dd9`: No such file or directory: OCI runtime attempted to invoke a command that was not found`

[1]: https://github.com/docker/awesome-compose/tree/master/flask

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Checkout awesome-compose repo
2. Install podman desktop (1.3.0-next), install podman 4.6.1.
3. Initialize and start podman machine (podman-machine-default - gonna be rootless)
4. Install compose via download button (2.20.3)
5. Set it to be installed system wide
6. Open Cli and check availability of docker-compose.exe on a PATH
7. checkout to a folder with `flask` sample
8. Run `DOCKER_HOST=npipe:////./pipe/podman-machine-default docker-compose.exe up -d`
9. Assert: flask container are spin up correctly. 
Actual result: 
```
Error response from daemon: crun: creating cgroup directory `/sys/fs/cgroup/misc/docker/buildx/libpod-e8e918dd83ea5605e3b70e5c37ccd65262eb0534377fb56d8ca29d02058f3dd9`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

### Relevant log output

```shell
$ DOCKER_HOST=npipe:////./pipe/podman-machine-default docker-compose.exe up -d
#0 building with "default" instance using docker-container driver

#1 [web internal] booting buildkit
#1 starting container buildx_buildkit_default
#1 starting container buildx_buildkit_default 0.6s done
#1 ERROR: Error response from daemon: crun: creating cgroup directory `/sys/fs/cgroup/misc/docker/buildx/libpod-e8e918dd83ea5605e3b70e5c37ccd65262eb0534377fb56d8ca29d02058f3dd9`: No such file or directory: OCI runtime attempted to invoke a command that was not found
------
 > [web internal] booting buildkit:
------
Error response from daemon: crun: creating cgroup directory `/sys/fs/cgroup/misc/docker/buildx/libpod-e8e918dd83ea5605e3b70e5c37ccd65262eb0534377fb56d8ca29d02058f3dd9`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

### Additional context

This is a sub issue for a #3535 which should help identify core problems with a compose. Could be upstream issue.

**Comment by cdrage** [comment] 2023-08-21 13:44
On the new machine, were you able to reproduce this issue @odockal ?

I see that https://github.com/containers/podman/issues/17042 was created, but want to confirm 100% if it's our end (PD) or not

**Comment by cdrage** [comment] 2023-08-28 18:36
Closing this for now as I've just tried again and was unable to reproduce it. 

I followed the same steps, but instead of getting: `Error response from daemon: crun: creating cgroup directory `/sys/fs/cgroup/misc/docker/buildx/libpod-e8e918dd83ea5605e3b70e5c37ccd65262eb0534377fb56d8ca29d02058f3dd9`: No such file or directory: OCI runtime attempted to invoke a command that was not found`

I was able to successfully bring up the flask application. 

Let me know if this is still an issue and we'll re-open it!

**Closed as completed by cdrage** 2023-08-28 18:36 UTC
Labels: engine/podman 🦭, sprint/unplanned, area/extensions/compose 🎹

**Comment by BjoernAkAManf** [comment] 2023-10-27 12:19
Still running into this issue.
However this only occurs if podman requires to build.

This does not work:

docker-compose.yml
```yaml
services:
#  alpine:
#    image: alpine:latest
  poc:
    build:
      context: poc
      args:
        VERSION_ALPINE: '3.18'
```

nginx/Dockerfile
```Dockerfile
ARG VERSION_ALPINE=latest
FROM alpine:${VERSION_ALPINE} as builder
```

This however does work:
```yaml
services:
  alpine:
    image: alpine:latest
#  poc:
#    build:
#      context: poc
#      args:
#        VERSION_ALPINE: '3.18'
```

Building the Dockerfile also works:

podman build poc 

Unsure if this is a Desktop issue, but i'd assume this is the same issue as above.

**Comment by krisdante** [comment] 2023-11-20 15:50
I have the same on WIndows

**Comment by jeffmaury** [comment] 2023-11-20 17:51
The command to use is `podman compose up -d` and not docker-compose up -d as buildkit is not supported.

**Comment by yunnysunny** [comment] 2024-01-18 15:10
> I have the same on WIndows

+1

**Comment by joaoopereira** [comment] 2024-01-21 22:07
I had the same issue today, but after running `podman machine set --rootful` solved the issue

**Comment by SohanTirpude** [comment] 2024-03-31 19:03
> I had the same issue today, but after running `podman machine set --rootful` solved the issue

@joaoopereira, I tried your way but still I am seeing the same issue for `celery`. This is the exact error:
```
Error: unable to start container "c2e86e1945532d0cec3a3379582b4f30bea43d790462d3277f79f1d6e2587244": crun: executable file `celery` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
exit code: 125
```

**Comment by joaoopereira** [comment] 2024-04-07 23:58
@SohanTirpude what are you trying to run?

**Comment by SohanTirpude** [comment] 2024-04-11 16:57
@joaoopereira please ignore. I managed to solve somehow but I don't remember now. Thanks anyway.
