### ISSUE TITLE
Add a page to get information about the docker compatibility

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#8304] opened 2024-07-31 14:48 UTC
### Is your enhancement related to a problem? Please describe

It might be difficult for now to know what is happening when using the docker CLI
(which socket will it use, will it use podman socket or not, if compose is working or not)

here is the list of tasks:
- [x] https://github.com/containers/podman-desktop/issues/9024
- [x] https://github.com/containers/podman-desktop/issues/9025
- [x] https://github.com/containers/podman-desktop/issues/9026

### Describe the solution you'd like

Have indicator in a page where we know about the compatibility mode of Podman
- can we turn it on or off
- compose is installed or not
- what are the sockets used by CLIs (podman and docker)

### Describe alternatives you've considered

How to build this kind of page while information will come from multiple sources

- podman extension
- compose extension
etc.

**Comment by Firewall** [comment] 2024-09-24 14:13
The subtasks here have been moved to the Epic, this epic is a duplicate of https://github.com/containers/podman-desktop/issues/8337

**Closed as completed by Firewall** 2024-09-24 14:13 UTC
Labels: duplicate, area/settings ⚙️
