### ISSUE TITLE
Mac Os Airgapped installer always uses qemu base image even if applehv provider is being used with podman v4

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6674] opened 2024-04-05 11:06 UTC
### Bug description

On Mac os, the airgapped installer for podman desktop always uses qemu base image for a podman machine, even though I am using `applehv` provider. The machine then cannot be started from Podman Desktop.

Listing of the `machine.json` (~/.config/containers/podman/machine/applehv/machine.json) show that the image has format expected for qemu: `podman-machine-default_podman-image-amr64.qcow2` whilst, if I create a machine via command line I get the format and suffix like this: `*-applehv-aarch64.raw`

### Operating system

Mac OS 14

### Installation Method

Installer from website/GitHub releases

### Version

1.9.0

### Steps to reproduce

1. Install podman v4
2. Setup applehv as a container provider (`~/.config/containers/containers.conf`)
3. Download and install vfkit
4. Install and start podman desktop airgapped (1.9.1)
5. Create new podman machine
6. Assert: machine is created and started
Actual result: Something like: `Error: Command execution failed with exit code 125` and `vfkit command failed with exit code 0`

### Additional context

Workaround: 
Updating podman to v5 solve the problem.

**Comment by benoitf** [comment] 2024-04-24 17:27
cc @containers/podman-desktop-qe-reviewers  if you could check that the problem is fixed with 1.10-next version

**Comment by odockal** [comment] 2024-04-25 15:14
@benoitf Works now.

**Comment by odockal** [comment] 2024-04-25 15:17
For future reference, in order to build Airgapped installed on Mac OS:
```
yarn install
AIRGAP_DOWNLOAD=true yarn compile:current
# Install produced dmg file
# sign the airgapped application so it can be run
codesign --deep --force --sign - Podman\ Desktop.app
# now you can start using locally built airgapped pd.
```

**Closed as completed** 2024-04-25 15:44 UTC
Labels: engine/podman 🦭, os/macOS 🍎
