### ISSUE TITLE
Updating Podman Desktop crashes the app on Windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7114] opened 2024-05-06 14:47 UTC
### Bug description

Updating Podman Desktop 1.9.1 to the latest available crashes the running podman desktop instance. The update works from version 1.8.0 to the latest.

Edit: update also work for 1.10.0 -> 1.10.2

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Steps to reproduce

1. Install podman desktop 1.9.1
2. When opened, you should be asked to install update
3. Accept installation of the updated version
4. ASSERT: Podman desktop is updated to the 1.10.2
Actual result: app crashes

Workaround, install podman desktop 1.10.2 manually
Update from 1.8.0 works fine

### Relevant log output

```shell
Activating extension (podman-desktop.kind) ended in 1139 milliseconds
PluginSystem: initialization done.
Autostarting podman-desktop.podman container engine
Installing Podman Desktop startup file at C:\Users\Ondrej\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\podman-desktop.vbs using C:\Users\Ondrej\AppData\local\Programs\podman-desktop\Podman Desktop.exe location.
Fetched https://registry.podman-desktop.io/api/extensions.json in 51.673799991607666ms
Found version 1.10.2 (url: podman-desktop-1.10.2-setup.exe, podman-desktop-1.10.2-setup-x64.exe, podman-desktop-1.10.2-setup-arm64.exe)
Downloading update from podman-desktop-1.10.2-setup.exe, podman-desktop-1.10.2-setup-x64.exe, podman-desktop-1.10.2-setup-arm64.exe
updater cache dir: C:\Users\Ondrej\AppData\Local\podman-desktop-updater
Download block maps (old: "https://github.com/containers/podman-desktop/releases/download/v1.9.1/podman-desktop-1.9.1-setup.exe.blockmap", new: https://github.com/containers/podman-desktop/releases/download/v1.10.2/podman-desktop-1.10.2-setup.exe.blockmap)
disableWebInstaller is set to false, you should set it to true if you do not plan on using a web installer. This will default to true in a future version.

<--- Last few GCs --->

[8008:000012A800138000]    11373 ms: Scavenge 3322.8 (3461.9) -> 3322.5 (3461.9) MB, pooled: 0 MB, 1.98 / 0.00 ms  (average mu = 0.996, current mu = 0.995) allocation failure;
[8008:000012A800138000]    11375 ms: Scavenge 3322.5 (3461.9) -> 3322.6 (3461.9) MB, pooled: 0 MB, 1.68 / 0.00 ms  (average mu = 0.996, current mu = 0.995) allocation failure;


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

[8008:000012A800138000]    11373 ms: Scavenge 3322.8 (3461.9) -> 3322.5 (3461.9) MB, pooled: 0 MB, 1.98 / 0.00 ms  (average mu = 0.996, current mu = 0.995) allocation failure;
[8008:000012A800138000]    11375 ms: Scavenge 3322.5 (3461.9) -> 3322.6 (3461.9) MB, pooled: 0 MB, 1.68 / 0.00 ms  (average mu = 0.996, current mu = 0.995) allocation failure;


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 00007FF72328FF96
 2: 00007FF723290209
 3: 00007FF7265CB534
 4: 00007FF7265CB4A3
 5: 00007FF72667BA37
 6: 00007FF721C88891
 7: 00007FF721C88248
 8: 00007FF721C87EA0
 9: 00007FF721C8D90F
10: 00007FF724790D07
11: 00007FF723B162AC
12: 00007FF72331CE27
13: 00007FF725AE19EA
14: 00007FFBFB887344
15: 00007FFBFD4826B1
```

### Additional context

https://github.com/electron-userland/electron-builder/issues/7921

**Comment by benoitf** [comment] 2024-05-07 04:46
The workaround for Windows users is to download the file manually from https://podman-desktop.io/downloads/windows

**Comment by dgolovin** [comment] 2024-05-07 06:36
It seems the problem is in electron-builder auto updater, not podman-desktop itself.

**Comment by ScrewTSW** [comment] 2024-05-27 10:14
Confirmed downloader task present in 1.10.3-next

**Comment by odockal** [comment] 2024-05-27 11:52
> Confirmed fixed in 1.10.3-next

The issue will never be fixed as one simply cannot update from 1.9.1, the issue is in that particular version. Users need to reinstall the podman-desktop, not update from 1.9.1. From 1.10.x update works again.

**Comment by odockal** [comment] 2024-07-03 14:07
I tried again to update 1.10.3 to 1.11.1 which went well on windows. Although, I tried (luckily) to update from 1.11.0 to 1.11.1 which crashed. We might see a problem when going to release 1.12.x.

**Comment by odockal** [comment] 2024-08-13 06:50
And so we see the problem updating to 1.12.0.

**Comment by benoitf** [comment] 2024-10-09 09:49
closing as now there are tests to ensure future updates are working.

in cases you're facing the issues on new builds, you need to manually download the file from https://podman-desktop.io/downloads/windows

**Closed as completed by benoitf** 2024-10-09 09:49 UTC
Labels: os/windows 🪟, sprint/unplanned, area/update

**Comment by odockal** [comment] 2024-10-16 15:19
It is worth mentioning that automation was set after 1.12.0 release and so it seems that update from 1.12.0 also has this problem.

**Comment by AndreaLombardo** [comment] 2025-01-31 08:07
Issue is still here while updating from 1.15.0 to 1.16.0. Every time must download and install newer version from its installer.

**Comment by benoitf** [comment] 2025-01-31 08:32
@AndreaLombardo are you on Windows or macOS ? (also do you have custom extensions being installed)

we're still investigating the issue but there is not a 100% reproducer case on our end with vanilla/default extensions install.

**Comment by AndreaLombardo** [comment] 2025-01-31 08:46
I'm on Windows and this is my situation (after installation from setup) so maybe next time I'll wait before manually update and share some other infos:

```
Compose extension
compose extension details
ACTIVE
built-in Extension
Compose extension
compose extension details
Install Compose binary to work with Podman
Podman Desktop built-in extension
v1.16.0

Docker extension
docker extension details
DISABLED
built-in Extension
Docker extension
docker extension details
Integration for Docker engine
Podman Desktop built-in extension
v1.16.0

Kind extension
kind extension details
DISABLED
built-in Extension
Kind extension
kind extension details
Integration for Kind: run local Kubernetes clusters using container “nodes”
Podman Desktop built-in extension
v1.16.0

Kube Context extension
kube-context extension details
ACTIVE
built-in Extension
Kube Context extension
kube-context extension details
Easily switch between Kubernetes contexts
Podman Desktop built-in extension
v1.16.0

kubectl CLI extension
kubectl-cli extension details
ACTIVE
built-in Extension
kubectl CLI extension
kubectl-cli extension details
Install and update kubectl CLI Tools without leaving Podman Desktop
Podman Desktop built-in extension
v1.16.0

Lima extension
lima extension details
ACTIVE
built-in Extension
Lima extension
lima extension details
Integration for Lima: Linux Machines (typically macOS)
Podman Desktop built-in extension
v1.16.0

Podman extension
podman extension details
ACTIVE
built-in Extension
Podman extension
podman extension details
Integration for Podman and Podman Machines
Podman Desktop built-in extension
v1.16.0

Podman AI Lab extension
ai-lab extension details
DISABLED
Podman AI Lab extension
ai-lab extension details
Podman AI Lab lets you work with LLMs locally, exploring AI fundamentals, experimenting with models and prompts, and serving models while maintaining data security and privacy.
v1.3.4

Registries extension
registries extension details
ACTIVE
built-in Extension
Registries extension
registries extension details
Adds default registries for Quay, DockerHub, GitHub, and Google Container Registry
Podman Desktop built-in extension
v1.16.0
```

**Comment by benoitf** [comment] 2025-01-31 09:00
Thanks for the detailed report

**Comment by odockal** [comment] 2025-02-05 08:44
@AndreaLombardo Possible workaround for now:
1. Disabled AI Lab
2. Option1: In Preferences toggle Exit on Close to be active (The only point is to make sure we quit Podman Desktop) and close the app
2. Option 2: Quit Podman Desktop (for example using system tray Quit Option)
3. Start Podman Desktop again
4. Perform Update

I tested this path multiple times on my machine, so if you can try this as well, please, and let us know, how it went. Thank you!

Otherwise, we have opened the issue where the problem is being investigated https://github.com/podman-desktop/podman-desktop/issues/10725, I think it is wise to follow up there since this one was resolved (upstream bug) and now we are facing problem with extension dependency which is different, imho.
