### ISSUE TITLE
Creating new (another one) podman machine on Mac Os: Error - cannot overwrite connection

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2793] opened 2023-06-09 14:15 UTC
### Bug description

Tried to create another podman machine when there was already one initial running after fresh installation. Got "Error: Cannot overwrite connection". No specific console log.

### Operating system

mac OS ventura 13 (Intel)

### Version

1.1.0

### Steps to reproduce

1. fresh install Podman Desktop
2. install podman
3. Initialize and start podman machine
4. Create new podman machine
Assert: second machine created, is in stopped state (guessing), no error
Actually I got an error in terminal during machine creation.

### Additional context

During step 3. (podman machine initialize and start) I run into #1633. So I restart podman desktop, it started then with running state of podman machine - visually it seemed alright.

**Comment by odockal** [comment] 2023-06-09 15:52
Second time after application restart I managed to create new machine.

**Comment by odockal** [comment] 2023-06-09 17:23
I am betting that the issue was with a "wrong" connection that was used by the podman. It was not root connection but the default one for given machine. Probably caused by https://github.com/containers/podman-desktop/issues/2582

**Comment by benoitf** [comment] 2023-06-13 07:37
Duplicate of https://github.com/containers/podman/issues/13165

**Closed as completed by benoitf** 2023-06-13 07:37 UTC
Labels: engine/podman 🦭, os/macOS 🍎
