### ISSUE TITLE
Kubernetes Dashboard Generates Significant Amount Of Traffic

### ISSUE THREAD

**Issue by MichaelGerhart** [containers/podman-desktop#10063] opened 2024-11-22 05:07 UTC
### Bug description

Our organization migrated to Podman Desktop ~1 year ago away from Docker Desktop to avoid licensing costs. So in my context, I have hundreds of developers with Podman Desktop installed.

We have encountered a scenario with Podman Desktop 1.14+ (Specifically with the new kubernetes dashboard functionality), where developers with a valid kubeconfig in their path started generating a significant amount of traffic to the kube API server of multiple clusters causing stability issues for those cluster control planes (IE outages), after discovering the node agent these requests are made with (node-fetch) we blocked the user agent to restore stability to the clusters and effectively block podman Desktop.

I believe the default behavior of this functionality either needs to be ratcheted down so its not making so many API requests by default, or conversely make the dashboard refreshable manually with the option to enable automatic refreshed.

### Operating system

MacOS 14

### Installation Method

Installer from website/GitHub releases

### Version

1.14.0

### Relevant log output

```shell
<redacted source IP> - - [22/Nov/2024:04:30:32 +0000] "GET /k8s/clusters/<redacted>/api/v1/namespaces/<redacted>/services?watch=true&resourceVersion=5515861643 HTTP/1.1" 200 240 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 386 21.571 [cattle-system-rancher-80] [] 10.254.3.193:80 240 21.571 500 aa6661c2be0b717ae64a7c7929d3cb7e
```

**Comment by feloy** [comment] 2024-11-22 06:20
Thanks @MichaelGerhart for this report.

I'll develop in an upcoming message (to try to find the root cause of the problem), but as a first workaround, a possibility to not block the user agent at the server-level would be to "de-activate" the kubernetes functionality from some or all Podman Desktop installations, by changing the path of the kubeconfig file for these installs, to indicate a non existing file, so the functionality will be disabled on these installs.

Users can change it by going to Settings > Preferences > Kubernetes > Kubeconfig, and setting a non-existing file (/tmp/non-existing for example)

This way, some users may still have access to the Kubernetes functionality in Podman Desktop, while de-activating it for the users not willing to use it.

**Comment by feloy** [comment] 2024-12-16 13:45
The traffic should be greatly reduced with https://github.com/podman-desktop/podman-desktop/pull/10335 (only the current context will be monitored)

**Comment by feloy** [comment] 2024-12-23 08:00
> The traffic should be greatly reduced with [#10335](https://github.com/podman-desktop/podman-desktop/pull/10335) (only the current context will be monitored)

Closing as fixed, please reopen it if it still happens with the upcoming version 1.16

**Closed as completed by feloy** 2024-12-23 08:00 UTC
