### ISSUE TITLE
Podman Desktop doesn't install the latest released version of an an extension

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2629] opened 2023-05-25 09:23 UTC
### Bug description

OpenShift Local version 1.0.3 has been released https://github.com/crc-org/crc-extension/releases/tag/v1.0.3, but Podman Desktop installs v1.0.1.

### Operating system

Linux

### Version

1.0.x

### Steps to reproduce

1. Go tp **Dashboard > Featured extensions > OpenShift Local** tile.
2. Click the download button.
3. OpenShift Local extension is installed.
4. Go to **Settings > Resources > Extensions**: `Red Hat OpenShift Local (user) v1.0.1` is installed (Expected: the latest released version of the extension, 1.0.3).

**Comment by jeffmaury** [comment] 2023-05-25 09:56
Not a bug the catalog is not updated yet

**Comment by gbraad** [comment] 2023-05-25 10:24
@jeffmaury we addressed critical issues in v1.0.2... which means they are not used?
Is there some way to make the releases of the extension decoupled from the catalog or at least download 'latest' instead?!

Re-opening for this reason.

**Comment by benoitf** [comment] 2023-05-25 10:34
closing as 1.0.2 is the one people are getting now. It's just 1.0.1 is displayed because of https://github.com/crc-org/crc-extension/issues/136

And catalog is decouple to ensure consistency

**Closed as not planned by benoitf** 2023-05-25 10:34 UTC
Labels: status/need-triage

**Comment by gbraad** [comment] 2023-05-25 10:42
> > And catalog is decouple to ensure consistency
> closing as 1.0.2 is the one people are getting now. 

What about v1.0.3 ?!?

**Comment by jeffmaury** [comment] 2023-05-25 11:19
See https://github.com/containers/podman-desktop-catalog/pull/8
