### ISSUE TITLE
kubectl CLI `Upgrade/Downgrade` shows unsorted versions quick pick list with `Kubernetes` prefix

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#9221] opened 2024-10-04 17:14 UTC
### Bug description

The list should contain only versions and should be sorted starting with latest released version

![Image](https://github.com/user-attachments/assets/69f6a35e-e97e-4cce-9cd0-61c3cb60b033)

### Operating system

macOS Sequoia

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Open CLI settings
2. Select `Install` or `Upgrade/Downgrade` for kubectl CLI

**Comment by odockal** [comment] 2024-10-07 08:11
@dgolovin This is a dupe of https://github.com/containers/podman-desktop/issues/6652. The versions are sorted by release date. Or you think they are not? Also, seems like 1.30.5 is missing, which was released like a couple of weeks ago.

**Closed as completed** 2024-10-16 20:51 UTC
Labels: area/extension/kubectl-cli
