### ISSUE TITLE
There should be a way to specify arbitrary environment variables when starting a container

### ISSUE THREAD

**Issue by dylanmtaylor** [containers/podman-desktop#674] opened 2022-10-23 22:37 UTC
### Is your enhancement related to a problem? Please describe

Certain containers need environment variables set to function correctly

### Describe the solution you'd like

Under port mapping in the create container dialog, add an environment variables section with a (+) button to enter the name and value and a (-) button to remove ones accidentally added or no longer desired.

### Additional context

As an example, this is required to run the mysql container through the podman desktop interface. Without a variable set, it immediately exits. 

![image](https://user-images.githubusercontent.com/277927/197421556-c1a9e9d2-99da-4097-8414-689286c2a2b9.png)
![image](https://user-images.githubusercontent.com/277927/197421577-e3ad3942-7d37-4175-ace7-4336ba1cff77.png)

**Comment by benoitf** [comment] 2022-10-24 07:14
Hi @dylanmtaylor 
Agreed and I think it's a subtask of https://github.com/containers/podman-desktop/issues/375

**Comment by benoitf** [comment] 2022-10-24 07:14
closing as duplicate of https://github.com/containers/podman-desktop/issues/375

**Closed as not planned by benoitf** 2022-10-24 07:14 UTC
