### ISSUE TITLE
UI not initializing after running Podman Desktop from main, ReferenceError present

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#3314] opened 2023-07-24 09:22 UTC
### Bug description

After running Podman Desktop from main, the UI does not load.
![Screenshot from 2023-07-24 11-12-11](https://github.com/containers/podman-desktop/assets/57829934/b00d3cb9-41d3-42f2-865c-d95d9d209197)

### Operating system

Linux

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. pull the latest version of main (current last commit: 9dbdcde9b6aa9c28ac8cdd9d718dea7ab3970fa0)
2. run `yarn install` and `yarn compile`
3. run `dist/linux-unpacked/podman-desktop` or `yarn watch`

### Relevant log output

```shell
Uncaught ReferenceError: __dirname is not defined
    at node_modules/electron/index.js (index.js:4:28)
    at __require2 (chunk-QUWOTVNT.js?v=e40f4b20:19:50)
    at index.js:21:34

(from yarn watch)
```

**Comment by lstocchi** [comment] 2023-07-24 09:24
closing as duplicate of https://github.com/containers/podman-desktop/issues/3310
it is fixed by https://github.com/containers/podman-desktop/pull/3312

**Closed as completed by lstocchi** 2023-07-24 09:24 UTC
Labels: status/need-triage
