### ISSUE TITLE
Adapt the proposed podman machine name when starting a second podman machine

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2426] opened 2023-05-10 11:25 UTC
### Is your enhancement related to a problem? Please describe

When creating a Podman machine from **Settings > Resources**, Podman Desktop proposes the name: `podman-machine-default` regardless of the existence of a Podman machine already present with that name.

If you click on **Create** you receive the following message:

```
Error: Error: podman-machine-default: VM already exists
```

### Describe the solution you'd like

Podman Desktop should:
1. Detect the presence of a Podman machine with the default `podman-machine-default` name before displaying the creation screen.
2. Propose another name for the machine if the default name if used.

**Comment by benoitf** [comment] 2023-05-10 13:37
closing as duplicate of https://github.com/containers/podman-desktop/issues/1189

**Closed as not planned by benoitf** 2023-05-10 13:37 UTC
Labels: duplicate, engine/podman 🦭, area/extension/podman 🦭
