### ISSUE TITLE
Add ARIA functionality to image/containers/pods table rows

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#5639] opened 2024-01-22 16:54 UTC
### Is your enhancement related to a problem? Please describe

It's very difficult to handle image/container/pod table rows in their respective pages because there aren't any rows specific ARIA locators available.

### Describe the solution you'd like

Add ARIA functionality at the table tow level to allow for easy individual row selections.

**Comment by benoitf** [comment] 2024-01-22 21:27
might be a duplicate of https://github.com/containers/podman-desktop/issues/4967

**Comment by deboer-tim** [comment] 2024-01-22 21:53
Yes, I think it is (at least a subset).

Note that container list is the only one that's not using the table component now, and not clear when we'd update it atm. If we add labels there short term it should match what we do in the Table to avoid breaking E2E tests when it does move.

**Closed as completed** 2024-04-18 11:40 UTC
Labels: area/tests 🚦
