### ISSUE TITLE
Remove redundant buttons on details page

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#497] opened 2022-09-28 20:30 UTC
### Bug description

This isn't really a 'bug', but didn't fit in other categories either.

On the Container details page, there are buttons for Terminal and Kube.
On the Images details page, there's a button for Show History.

IMHO, these make sense as quick-links on the Containers and Images pages, but are redundant once you're on the page itself, when the tabs themselves are visible and just as easy to click. Someone might argue that consistency of buttons between the pages is important, but for me they are out of place - UI clutter, and you have to scan through more buttons to find the one you want.

### Operating system

macOS 12.6

### Version

0.8.0

**Comment by deboer-tim** [comment] 2022-09-28 20:31
FYI @mairin

**Comment by benoitf** [comment] 2022-09-28 20:35
moving to enhancement as it's not a bug

**Comment by slemeur** [comment] 2022-09-29 09:37
+1

**Closed as completed** 2023-01-19 10:11 UTC
Labels: area/dashboard 📊
