### ISSUE TITLE
AlmaLinux 9 - PodMan Desktop installation via FlatPak - Preferences default on Each Launch

### ISSUE THREAD

**Issue by rbargerhuff** [containers/podman-desktop#7083] opened 2024-05-03 18:47 UTC
### Bug description

Flatpak installation method is not allowing preferences to be saved between consecutive launches. Instead, the default values are being used. For example, if I disable extensions I know I will not be working with, when I relaunch Podman Desktop those extensions are reenabled.

### Operating system

AlmaLinux 9

### Installation Method

Other

### Version

1.9.x

**Comment by deboer-tim** [comment] 2024-05-03 18:54
Extensions not staying disabled after restart is a known issue that affects all platforms: #268. Could you confirm if all preferences are being reset, or if this is just a dupe of 268?

**Comment by rbargerhuff** [comment] 2024-05-03 19:07
> Extensions not staying disabled after restart is a known issue that affects all platforms: #268. Could you confirm if all preferences are being reset, or if this is just a dupe of 268?

Can confirm that just the Extensions and their disabled status are not being saved. I disabled "Auto Check Updates" and "Auto Update" preferences and those settings were set correcly after restarting Podman Desktop.

**Comment by deboer-tim** [comment] 2024-05-03 20:44
Ok, thanks for confirming. Closing as dupe of #268, I happened to be working on it this afternoon so hopefully the PR will get merged soon.

**Closed as not planned by deboer-tim** 2024-05-03 20:44 UTC
Labels: status/need-triage
