### ISSUE TITLE
Command `Kube: Switch Context ...` should show error message using window API not console

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#5889] opened 2024-02-07 06:34 UTC
### Bug description

If there is no active kubernetes cluster `Kube: Switch Context ...` shows errors or warnings to the user. It prints all errors to consloe. The command should show error message using `window` API.

### Operating system

macOS Sonoma 14.3

### Installation Method

Installer from website/GitHub releases

### Version

1.7.0

### Steps to reproduce

1. Show palette
2. Call command 'Kube: Swithch context...`
3. Nothing happens, but console has multiple errors reported

### Relevant log output

```shell
main ↪️ Kube pod event error Error: No currently active cluster
    at Watch.watch (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/watch.js:51:19)
    at TS.setupKubeWatcher (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:237:4978)
    at TS.refresh (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:237:8675)
    at async /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:237:4449
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
VM5:2 main ↪️ Kube deployment event error Error: No currently active cluster
    at Watch.watch (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/watch.js:51:19)
    at TS.setupKubeWatcher (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:237:5187)
    at TS.refresh (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:237:8675)
    at async /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:237:4449
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
4index.html:1 Uncaught (in promise) Error: No active cluster!
```
```


### Additional context

_No response_

**Comment by benoitf** [comment] 2024-02-07 08:53
I think you don't need to open an issue for each command being defined as part of the onboarding flow

AFAIK we have an issue telling to hide these commands from the command palette view

**Comment by benoitf** [comment] 2024-02-07 08:54
duplicate of https://github.com/containers/podman-desktop/issues/5148

**Closed as completed by benoitf** 2024-02-07 08:54 UTC
Labels: status/need-triage
