### ISSUE TITLE
Odd image hover resizing

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#135] opened 2022-05-11 13:39 UTC
### Bug description

The images page layout gets funky when the window is small and you hover over items.

### Operating system

macOS 12.3.1 M1

### Version

next (development version)

### Steps to reproduce

Make the window smallish and hover over items. See attached video.

https://user-images.githubusercontent.com/19958075/167863474-9265a4a9-9d43-4e8e-aca2-b1599da6fe8d.mov

**Comment by benoitf** [comment] 2022-06-10 16:06
Duplicate of https://github.com/containers/podman-desktop/issues/179

**Closed as completed by benoitf** 2022-06-10 16:06 UTC
