### ISSUE TITLE
Blank page when deleting Kind from Settings > Resources > Kind > Details

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#3594] opened 2023-08-17 23:57 UTC
### Bug description

If you create a Kind cluster, go to its Details page, stop it, and delete it, the page goes blank. As far as I can tell there are no ill effects, you just need to navigate to another page. (so IMHO no need to back-port to 1.3.x)

I've confirmed the identical fix to #3576 works when applied to PreferencesKubernetesConnectionRendering, it just needs a similar test written too.

### Operating system

macOS 13.5

### Installation Method

None

### Version

next (development version)

**Comment by benoitf** [comment] 2023-08-23 13:19
so here it's not a bug as we we're correctly handling the case with connection being undefined. It's just that we're not redirecting to the previous page

moving to an enhancement

**Closed as completed** 2023-08-24 07:33 UTC
Labels: area/dashboard 📊, sprint/unplanned, area/extension/kind 🍾
