### ISSUE TITLE
Some way to know that a container was created

### ISSUE THREAD

**Issue by Luxvao** [containers/podman-desktop#788] opened 2022-11-08 08:12 UTC
### Is your feature request related to a problem? Please describe

I tried to create a container with the GUI and nothing seemed to happen. (the container didn't show up under the containers tab as I mention in a issue I posted before) There was no "Container created successfully" or something like that. I ended up creating a lot of random containers I didn't even know existed until I ran `podman ps -a`

### Describe the solution you'd like

There could be like a little popup let's say in green, that says "Container created successfully"

**Comment by benoitf** [comment] 2022-11-08 10:35
@Luxvao the container should appear on the list once you create the container

so the bug is https://github.com/containers/podman-desktop/issues/787

if the container is not being able to be created you see the error message

Closing this bug as https://github.com/containers/podman-desktop/issues/787 is the root cause

**Closed as not planned by benoitf** 2022-11-08 10:35 UTC
