### ISSUE TITLE
support managing volumes

### ISSUE THREAD

**Issue by lethargosapatheia** [containers/podman-desktop#448] opened 2022-09-05 11:09 UTC
### Is your feature request related to a problem? Please describe

On the one hand I would like to be able to browse the files and folders of container volumes using podman desktop. On top of that it would be great if I could generally manage volumes (e.g. create, delete) and see what containers are currently using them.

### Describe the solution you'd like

Have a new section like 'Volumes' (like in Docker Desktop) where you can manage them.

### Additional context

Mac OS Monterey 12.5.1
podman 4.2.0
podman desktop 0.0.6 (installed through brew)

**Comment by benoitf** [comment] 2022-09-05 11:39
Hello, I'm closing this issue as it's a duplicate of https://github.com/containers/podman-desktop/issues/392

you may comment https://github.com/containers/podman-desktop/issues/392 to add extra details

**Closed as not planned by benoitf** 2022-09-05 11:39 UTC
