### ISSUE TITLE
Podman Remote detection issues in CI

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop#10022] opened 2024-11-20 14:51 UTC
### Bug description

Podman Remote machine detection fails during test execution, or remote machine is in degraded state

### Operating system

macOS (?), ubuntu

### Installation Method

Other

### Version

next (development version)

### Relevant log output

```shell

```

**Comment by odockal** [comment] 2024-11-20 14:56
Dupe of: https://github.com/podman-desktop/podman-desktop/issues/9980.

**Closed as completed by odockal** 2024-11-20 14:56 UTC
Labels: area/tests 🚦
