### ISSUE TITLE
Docker Socket Compatibility  not work 

### ISSUE THREAD

**Issue by linkoog** [containers/podman-desktop#7354] opened 2024-05-29 10:58 UTC
### Bug description

error:    dockerSock does not point to the expected target:  ~/.docker/run/docker.sock
the real file location is   /var/run/docker.sock 

### Operating system

macOS Ventura 13.4 (Arm)

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

**Comment by nichjones1** [comment] 2024-06-03 13:18
Closed as this is a duplicate of 
https://github.com/containers/podman-desktop/issues/2630

**Closed as completed by nichjones1** 2024-06-03 13:18 UTC
Labels: os/macOS 🍎, area/docker-compatibility 🐳
