### ISSUE TITLE
Crash while "initializing..."

### ISSUE THREAD

**Issue by tanwald** [containers/podman-desktop#1080] opened 2022-12-21 20:31 UTC
### Bug description

The app gets stuck while it shows the screen that says "Initializing...".

### Operating system

Fedora 6.0.13-300.fc37.x86_64

### Version

0.10.0

### Steps to reproduce

flatpak run io.podman_desktop.PodmanDesktop

### Relevant log output

```shell
flatpak run io.podman_desktop.PodmanDesktop
Gtk-Message: 21:18:23.992: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:18:23.992: Failed to load module "pk-gtk-module"
Gtk-Message: 21:18:23.993: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:18:23.993: Failed to load module "pk-gtk-module"
[3:1221/211824.004478:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1221/211824.004504:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
(node:3) UnhandledPromiseRejectionWarning: Error: contexts[2].context.cluster is missing
    at /app/main/resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:151:23
    at Object.map (/app/main/resources/app.asar/node_modules/underscore/underscore-node-f.cjs:1342:22)
    at newContexts (/app/main/resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:131:24)
    at KubeConfig.loadFromString (/app/main/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:108:56)
    at KubeConfig.loadFromFile (/app/main/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:77:14)
    at G0.refresh (/app/main/resources/app.asar/packages/main/dist/index.9a7a52d9.js:102:6414)
    at G0.init (/app/main/resources/app.asar/packages/main/dist/index.9a7a52d9.js:102:5451)
    at Q8.initExtensions (/app/main/resources/app.asar/packages/main/dist/index.9a7a52d9.js:127:14905)
    at async /app/main/resources/app.asar/packages/main/dist/index.9a7a52d9.js:153:1961
(Use `podman-desktop --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Error: contexts[2].context.cluster is missing
    at /app/main/resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:151:23
    at Object.map (/app/main/resources/app.asar/node_modules/underscore/underscore-node-f.cjs:1342:22)
    at newContexts (/app/main/resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:131:24)
    at KubeConfig.loadFromString (/app/main/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:108:56)
    at KubeConfig.loadFromFile (/app/main/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:77:14)
    at G0.refresh (/app/main/resources/app.asar/packages/main/dist/index.9a7a52d9.js:102:6414)
    at /app/main/resources/app.asar/packages/main/dist/index.9a7a52d9.js:102:6086
    at /app/main/resources/app.asar/packages/main/dist/index.9a7a52d9.js:79:19112
    at Z3.invoke (/app/main/resources/app.asar/packages/main/dist/index.9a7a52d9.js:79:19216)
    at zt.fire (/app/main/resources/app.asar/packages/main/dist/index.9a7a52d9.js:81:293)
PluginSystem: received dom-ready event from the UI
```

### Additional context

Since one or two versions of podman desktop.

**Comment by benoitf** [comment] 2022-12-21 20:33
Hello, it looks like a dup of https://github.com/containers/podman-desktop/issues/951

You may try to use a pre-release version as it'll be fixed in 0.11
https://github.com/containers/podman-desktop/releases

(Or fix the kubeconfig file)

**Comment by tanwald** [comment] 2022-12-21 20:48
Sorry, checked only open issues. My kubeconfigs are valid but I have more than one in $KUBECONFIG. I think the client doesn't know how to merge them. Could be an enhancement. Most other tools haven't complained, yet. I'll wait for 0.11...

**Comment by benoitf** [comment] 2022-12-21 20:50
we're using the official nodes k8s client library and this library performs a lot of verification checks :-/

**Comment by benoitf** [comment] 2022-12-22 08:54
closing as duplicate of https://github.com/containers/podman-desktop/issues/951

**Closed as not planned by benoitf** 2022-12-22 08:54 UTC
