### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to construct 'FormData': parameter 1 is not of type 'HTMLFormElement'.

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7755] opened 2024-06-20 11:37 UTC
### Bug description

While creating a Podman Machine (not sure if related at all, seen once) I have noticed the type error in console log.

```
Uncaught (in promise) TypeError: Failed to construct 'FormData': parameter 1 is not of type 'HTMLFormElement'.
```

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Relevant log output

```shell
PreferencesConnectio…endering.svelte:210 Uncaught (in promise) 
TypeError: Failed to construct 'FormData': parameter 1 is not of type 'HTMLFormElement'.
    at Q (PreferencesConnectio…ering.svelte:210:17)
    at E (PreferencesRendering…Format.svelte:109:3)
    at r.$$.update (FileItem.svelte:22:5)
    at he (Component.js:144:5)
    at new sme (FileItem.svelte:24:20)
    at Array.Cme (PreferencesRendering…ormat.svelte:139:54)
    at Array.bme (PreferencesRendering…ormat.svelte:138:52)
    at Rme (PreferencesRendering…ormat.svelte:143:39)
    at he (Component.js:148:34)
    at new Lp (PreferencesRendering…Format.svelte:33:34)
Q	@	PreferencesConnectio…endering.svelte:210
E	@	PreferencesRendering…emFormat.svelte:109
r.$$.update	@	FileItem.svelte:22
he	@	Component.js:144
sme	@	FileItem.svelte:24
Cme	@	PreferencesRendering…emFormat.svelte:139
bme	@	PreferencesRendering…emFormat.svelte:138
Rme	@	PreferencesRendering…emFormat.svelte:143
he	@	Component.js:148
Lp	@	PreferencesRenderingItemFormat.svelte:33
b7	@	PreferencesConnectio…endering.svelte:507
$7	@	PreferencesConnectio…endering.svelte:511
Ume	@	PreferencesConnectio…endering.svelte:496
Nme	@	PreferencesConnectio…endering.svelte:444
p	@	PreferencesConnectio…endering.svelte:537
fU	@	scheduler.js:119
VE	@	scheduler.js:79
Promise.then (async)		
DE	@	scheduler.js:20
dU	@	Component.js:81
(anonymous)	@	Component.js:139
(anonymous)	@	TaskManager.svelte:53
i	@	index.js:56
l	@	index.js:69
i0	@	tasks.ts:36
Zde	@	preferences-connecti…endering-task.ts:96
ce	@	PreferencesConnectio…endering.svelte:291
Se	@	PreferencesConnectio…endering.svelte:436
(anonymous)	@	lifecycle.js:181
vn	@	lifecycle.js:181
k	@	Button.svelte:25
```

**Comment by jeffmaury** [comment] 2024-07-31 07:59
Can't reproduce, can we close it ?

**Closed as completed** 2024-08-01 11:55 UTC

**Comment by odockal** [comment] 2024-08-02 14:23
@jeffmaury Sure, there is a fix for it linked.
