### ISSUE TITLE
Can't run Podman desktop with admin rights

### ISSUE THREAD

**Issue by AlexandrStarov** [containers/podman-desktop#9716] opened 2024-11-01 09:12 UTC
### Bug description

If I run the app with administrator rights, I can't open the dashboard
If I just run it, everything works.

The error can be seen if you run the application through PowerShell

Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92232)
    at _.send (node:electron/js2c/browser_init:2:75160)
    at C:\Users\aleksandr.starov\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:347:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

![Image](https://github.com/user-attachments/assets/9e0b78e2-52fb-497d-9353-220cc38e1696)
![Image](https://github.com/user-attachments/assets/ef18c2f6-4ee9-4d5d-88ab-ff3a419809e7)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.13.3

### Relevant log output

Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92232)
    at _.send (node:electron/js2c/browser_init:2:75160)
    at C:\Users\aleksandr.starov\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:347:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by AlexandrStarov** [comment] 2024-11-01 09:31
I tried to install version podman-desktop-1.11.0-setup-x64. As a result, I was able to launch the application

**Comment by odockal** [comment] 2024-11-12 10:03
@AlexandrStarov Hello, thanks for opening the issue. I have tried to reproduce the problem, but I was not successful with the information provided. Tried 1.13.3 and 1.14.1 that was installed from the msi installer (setup.exe) and I also tried directly run with admin right the executable version of the podman-desktop. I tried to have one instance opened and run another version as admin, also I have noticed a `dot` in your user name which might be a problem, so I tried to create similar user with a dot in the name, but still I was not able to reproduce. Although I have windows 10, other folks tested win 11 without issue.

Can you please try to clean up everything and install latest 1.14.1 version?
* Uninstall previous instance of podman-desktop via Programs
* remove `~/.local/share/containers/podman-desktop` -> will wipe out all particular settings and other podman-desktop related configuration

**Comment by axel7083** [comment] 2024-11-28 10:24
I am not able to reproduce. I compiled the portable version of podman-desktop and run it with admin privileged it. Everything seems to be working fine.

We could try to enhance the admin experience by adding a clear indicator. Podman Desktop could check if it is root/admin.

Let's take the example of the Windows Terminal

 ![Image](https://github.com/user-attachments/assets/2fce890d-f7fb-4f06-b4b7-081ee1cc76fa)

On the top the _shield_ and the title signify we are running in administrator mode, we could do something similar. Here is a quick mockup

![Image](https://github.com/user-attachments/assets/07bf594e-1ea4-4be8-88fe-a9333b20ed03)

**Comment by AlexandrStarov** [comment] 2024-11-28 12:52
@axel7083 I am currently using version 1.14.1 and everything works fine.

**Comment by axel7083** [comment] 2024-11-28 12:57
> [@axel7083](https://github.com/axel7083) I am currently using version 1.14.1 and everything works fine.

Thanks for the response, I will be closing the issue then 👍 , if you have any issue in the future don't hesitate to re-open, or comment on this one.

**Closed as not planned by axel7083** 2024-11-28 12:57 UTC
Labels: area/dashboard 📊, os/windows 🪟
