### ISSUE TITLE
Podman can create incredibly large stderr log

### ISSUE THREAD

**Issue by timReynolds** [containers/podman-desktop#1557] opened 2023-02-26 17:57 UTC
### Bug description

I install podman desktop a while back to evaluate it as a replacement for docker and haven't thought much about it since. When investigating why my new laptop had run out of space however it turns out the podman desktop stdlog file is consuming 270Gb. 
<img width="282" alt="Screenshot 2023-02-26 at 17 52 13" src="https://user-images.githubusercontent.com/168870/221427603-b341c204-c148-4afb-9cff-986aefcc170c.png">

There should probably be some throttling or rotation so this doesn't happen. 
<img width="959" alt="Screenshot 2023-02-26 at 17 52 49" src="https://user-images.githubusercontent.com/168870/221427642-9263491e-13f0-4153-8a6f-531b727271a8.png">

### Operating system

macOS 12 (M1)

### Version

0.12.0

**Comment by benoitf** [comment] 2023-02-26 19:56
@timReynolds yes it looks like we need to do something

**Comment by cdrage** [comment] 2023-03-24 14:08
Been trying to reproduce this, but found no way to create the launchd error logs.

It could perhaps be an older version that was running that created the logs, but then stopped after you upgraded.

Could you answer the following?
* Double check if it's 0.12.0
* Did you install via brew or website?
* Please delete the launchd-stderr.log and stdout and try opening Podman Desktop to see if they are created again. 

I'll try to reproduce it again (as I'm also on Mac M1), but on both the versioned as well as `yarn watch` I cannot seem to create the launchd logs (even with purposeful errors).

**Comment by cdrage** [comment] 2023-03-31 21:38
ping @timReynolds have you experienced this issue still?

**Comment by cdrage** [comment] 2023-04-26 14:48
Going to close this issue as wontfix / unproduceable. No other reports of the issue. May of been fixed with a recent Electron update, but I'm not entirely sure 🤷

**Closed as not planned by cdrage** 2023-04-26 14:48 UTC
Labels: area/dashboard 📊
