### ISSUE TITLE
No reply from server when testing httpbin app on Kind with ingress controller on Mac OS

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2216] opened 2023-04-25 12:41 UTC
### Bug description

I am not able to get a proper response (depending on request) from httpbin testing app. that I deployed on the kind cluster using Podman Desktop.

### Operating system

mac OS ventura 13.2 (Intel)

### Version

0.14.1

### Steps to reproduce

1. Install podman desktop
2. Install podman
3. Initialize and start podman machine
4. Download kind binary
5. Create cluster with ingress controller enabled (projectcontour) and default ports (9090)
6. Check that cluster is created
7. Download https://projectcontour.io/examples/httpbin.yaml and change replicas to 1
8. Play Kubernetes Yaml -> httpbin.yaml
9. Verify pod is created and running, you can check log
10. Access the service for httpbin via `localhost:9090`. Try `curl localhost:9090/status/200`
11. Expect response: 200
Actual result: curl: (52) Empty reply from server

**Comment by cdrage** [comment] 2023-04-25 12:53
> 7\. https://projectcontour.io/examples/httpbin.yaml

What happens when you run `kubectl apply -f https://projectcontour.io/examples/httpbin.yaml`

I'm assuming that it doesn't work if it's via "Play Kubernetes YAML", but probably works with `kubectl apply` ?

**Comment by jeffmaury** [comment] 2023-04-25 13:30
Looks like a duplicate of #2137 
Is the Ingress resource being created ?

**Comment by odockal** [comment] 2023-04-25 20:40
> Looks like a duplicate of #2137 Is the Ingress resource being created ?

There is the same bug/error message being shown, but it is not a problem really. 

Yes, Ingress is being enabled, and I checked using `kubectl get pods -A` and I can confirm, all pods (except the one we know is not running - projectcontour) are running.

>What happens when you run kubectl apply -f https://projectcontour.io/examples/httpbin.yaml
I'm assuming that it doesn't work if it's via "Play Kubernetes YAML", but probably works with kubectl apply ?

It actually works fine. If I skip to cli and use `kubectl apply -f ...` I got pod for httpbin up, serving the app, and Podman desktop shows it also up and running under Pods.

**Comment by odockal** [comment] 2023-04-25 20:44
If anyone wants to debug, I can provide the machine directly. Ask me via DM.

**Comment by odockal** [comment] 2023-04-25 20:46
There is only one warning among `kubectl -n default get events`.
Something like `Warning: FailedtoCreateEndpoint endpoint/httpbin Failed to create endpoint for service default/httpbin: endpoints "httpbin" already exists`. 

Which sound like a cause actually... :)

**Comment by benoitf** [comment] 2024-02-07 22:05
closing due to lack of recent comments

**Closed as not planned by benoitf** 2024-02-07 22:05 UTC
Labels: os/macOS 🍎, area/extension/kind 🍾
