### ISSUE TITLE
Unreadable setup parts in light mode (dark text on dark background)

### ISSUE THREAD

**Issue by ahus1** [containers/podman-desktop#8686] opened 2024-08-31 11:59 UTC
### Bug description

The boxed are unreadable:

![image](https://github.com/user-attachments/assets/7c802fa3-b7ec-467f-8e86-650744af3e0a)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

### Steps to reproduce

Install podman desktop on Windows 11 in light mode

**Comment by benoitf** [comment] 2024-09-02 07:16
closing as duplicate of https://github.com/containers/podman-desktop/issues/8447

**Closed as not planned by benoitf** 2024-09-02 07:16 UTC
Labels: status/need-triage
