### ISSUE TITLE
Objects on Nodes and other kubernetes pages disappear after a while

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7760] opened 2024-06-20 20:21 UTC
### Bug description

On windows, if I have some node available, ie. if I create a kind cluster (there is a node present) and open a node page, kind cluster node is visible. After a while, it disappear. I can bring it back if I switch the kube context to something else and back. 

![kuberentes_pages_objects_disappears](https://github.com/containers/podman-desktop/assets/19164299/1bac6541-c952-46b4-91e5-80d70a850c96)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Not easily reproducible. Have kind cluster available and then some other context to switch to and wait a few tens of seconds if kind-cluster context related resources disapper. I have seen it on both windows and linux. After windows went to sleep and was awaken, the problem is gone.

### Relevant log output

```
main ↪️ Trying to watch routes on the kubernetes context named "kind-kind-cluster" but got a connection refused, retrying the connection in 75s. HttpError: HTTP request failed)

main ↪️ Trying to watch deployments on the kubernetes context named "kind-kind-cluster" but got a connection refused, retrying the connection in 82s. Error: connect ECONNREFUSED 127.0.0.1:44953)

main ↪️ Trying to watch pods on the kubernetes context named "kind-kind-cluster" but got a connection refused, retrying the connection in 80s. Error: connect ECONNREFUSED 127.0.0.1:44953)

```

### Additional context

If I do not filter (I view all level) event level in console, I can see verbose level information as seen in above log output.

Output of kubectl seems alright:
```
kubectl get pods -A
NAMESPACE            NAME                                                 READY   STATUS      RESTARTS   AGE
kube-system          coredns-7db6d8ff4d-9t4rl                             1/1     Running     0          11h
kube-system          coredns-7db6d8ff4d-sqrl5                             1/1     Running     0          11h
kube-system          etcd-kind-cluster-control-plane                      1/1     Running     0          11h
kube-system          kindnet-tn94s                                        1/1     Running     0          11h
kube-system          kube-apiserver-kind-cluster-control-plane            1/1     Running     0          11h
kube-system          kube-controller-manager-kind-cluster-control-plane   1/1     Running     0          11h
kube-system          kube-proxy-dd8b4                                     1/1     Running     0          11h
kube-system          kube-scheduler-kind-cluster-control-plane            1/1     Running     0          11h
local-path-storage   local-path-provisioner-988d74bc-m2grp                1/1     Running     0          11h
projectcontour       contour-7d4b95459-q4vqh                              1/1     Running     0          11h
projectcontour       contour-7d4b95459-tn5dg                              1/1     Running     0          11h
projectcontour       contour-certgen-v1.24.2-9gvmw                        0/1     Completed   0          11h
projectcontour       envoy-8r9fg                                          2/2     Running     0          11h

kubectl get services -A
NAMESPACE        NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default          kubernetes   ClusterIP      10.96.0.1       <none>        443/TCP                      11h
kube-system      kube-dns     ClusterIP      10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP       11h
projectcontour   contour      ClusterIP      10.96.198.129   <none>        8001/TCP                     11h
projectcontour   envoy        LoadBalancer   10.96.29.174    <pending>     80:32314/TCP,443:31344/TCP   11h

kubectl get deployments -A
NAMESPACE            NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system          coredns                  2/2     2            2           11h
local-path-storage   local-path-provisioner   1/1     1            1           11h
projectcontour       contour                  2/2     2            2           11h

```

**Comment by jeffmaury** [comment] 2024-06-21 13:27
Tried several times to reproduce without success

**Comment by odockal** [comment] 2024-07-25 11:18
If no reproducing during next week, I will close issue.

**Comment by odockal** [comment] 2024-08-09 12:16
Happened during testing of 1.12.0 on Mac:

https://github.com/user-attachments/assets/64053e4f-7d5e-447d-98b2-a06a4654614f

**Comment by jeffmaury** [comment] 2024-08-12 11:33
I think it's related to devsandbox not allowing access to Nodes object, will check

**Comment by jeffmaury** [comment] 2024-08-26 14:50
Blocked by #8590

**Comment by jeffmaury** [comment] 2024-08-26 15:31
It seems you have deployed something on your Kind/Minikube cluster. Can you describe what have been deployed to ?

**Comment by jeffmaury** [comment] 2024-09-17 07:18
I managed to get it reproduce: created 2 Kubernetes contexts (minikube and DevSandbox) and wrote a script that switches context every second. After a while (about 1000s), Nodes pages is always empty but this is caused by Podman machine not responding anymore. As it was on WSL, I will try to reproduce on MacOS/Applehv as well

**Comment by odockal** [comment] 2024-09-17 12:39
Great that you have reproduced it. It never occurred on purpose. Just while playing with kubernetes cluster/resources during testing.

**Comment by odockal** [comment] 2024-09-19 10:07
@jeffmaury I am trying to reproduce the issue now, but no success so far. At least not on my Linux machine. I will see if I can reproduce on some machine in the labs so it can be examined.

**Comment by jeffmaury** [comment] 2024-11-27 13:37
@odockal ok to close this one ?

**Closed as completed** 2024-12-02 09:58 UTC
Labels: sprint/unplanned
