### ISSUE TITLE
Play kubernetes yaml DOM changed

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop#10023] opened 2024-11-20 14:55 UTC
### Bug description

Currently Play kubernetes yaml tests fail with unable to being locate `Done` button

### Operating system

any

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

* Execute yaml smoke test

### Relevant log output

```shell
Error: Timed out 120000ms waiting for expect(locator).toBeEnabled()

Locator: getByRole('button', { name: 'Done' })
Expected: enabled
Received: <element(s) not found>
Call log:
  - expect.toBeEnabled with timeout 120000ms
  - waiting for getByRole('button', { name: 'Done' })


   at tests/playwright/src/model/pages/play-kube-yaml-page.ts:100

   98 |       await this.yamlPathInput.fill(pathToYaml);
   99 |       await this.playButton.click();
> 100 |       await playExpect(this.doneButton).toBeEnabled({ timeout: 120000 });
      |                                         ^
  101 |       await this.doneButton.click();
  102 |       return new PodsPage(this.page);
  103 |     });

    at /Users/podmanqe/pd-e2e/podman-desktop/tests/playwright/src/model/pages/play-kube-yaml-page.ts:100:41
    at /Users/podmanqe/pd-e2e/podman-desktop/tests/playwright/src/specs/yaml-smoke.spec.ts:62:16
```

**Comment by odockal** [comment] 2024-11-25 09:01
Dupe of: https://github.com/podman-desktop/podman-desktop/issues/10010

**Closed as completed by odockal** 2024-11-25 09:01 UTC
Labels: area/tests 🚦
