### ISSUE TITLE
Bug  : in README ( inside Overview section)

### ISSUE THREAD

**Issue by ayushrakesh** [containers/podman-desktop#4414] opened 2023-10-19 04:04 UTC
### Bug description

I have spotted two same errors in different lines inside "Overview" section in README.md file.

"**Podman Desktop installs, configures and keeps...**"  should be "**Podman Desktop installs, configures, and keeps...**"   

and also
 
"**with containers, images, pods and volumes...**" should be "**with containers, images, pods, and volumes....**"

I have attached the screenshot below.

![Screenshot (75)](https://github.com/containers/podman-desktop/assets/115995339/c5314e3b-2fa2-4485-8eeb-b831c02fc2cf)

### Operating system

Windows 11

Please assign this issue to me.

**Comment by slemeur** [comment] 2023-10-19 06:28
Thank you @ayushrakesh

**Comment by afbjorklund** [comment] 2023-10-19 07:29
https://en.wikipedia.org/wiki/Oxford_comma

NOTABUG

**Comment by benoitf** [comment] 2023-10-19 07:52
yes Oxford comma is like spaces vs tabs but we're using both styles in the documentation so I'm fine changing and accepting contribution.
So yes not a bug, hoping it will collect more contribution and not only on the specific Oxford comma rule

**Comment by lstocchi** [comment] 2023-10-19 08:02
closed by #4415

**Closed as completed by lstocchi** 2023-10-19 08:02 UTC
