### ISSUE TITLE
Adjust registry e2e tests for new UI

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#8596] opened 2024-08-27 07:20 UTC
### Is your enhancement related to a problem? Please describe

Registry addition and handling now has different UI from when the tests were implemented.

### Describe the solution you'd like

Re-implement the tests to fit and pass the latest version of Podman Desktop.

**Comment by odockal** [comment] 2024-08-27 12:24
Dupe of #8026.

**Closed as completed by odockal** 2024-08-27 12:24 UTC
Labels: area/registries, area/tests 🚦
