### ISSUE TITLE
podman desktop unresponsive

### ISSUE THREAD

**Issue by sthapa** [containers/podman-desktop#1156] opened 2023-01-10 22:34 UTC
### Bug description

I'm using podman-desktop 0.10.0 from flathub.org on fedora 37 and came across something that's not necessarily a bug but looks like one.  

When podman-desktop starts up for the first time, there's a popup asking for consent to send telemetry to redhat.  However, the popup went behind the main podman desktop window.  Since the popup has control, it makes it look like the podman desktop app crashed since it doesn't respond to any input at all.  The user has to discover the hidden popup and dismiss it before the main window responds to input.

### Operating system

Fedora 37

### Version

0.10.0

### Steps to reproduce

* Start with a brand new install of podman-desktop (or delete the existing install and ~/.local/share/containers/podman-desktop and ~/.var/app/io.podman_desktop.PodmanDesktop)
* Install podman-desktop from flathub 
* run podman-desktop and see that the main window appears but doesn't respond to any input
* bring the telemetry popup from behind the main window and click ok
* main window now accepts inputs

**Comment by benoitf** [comment] 2023-01-11 08:13
thanks @sthapa for the report
this is indeed a problem
But it's already reported here https://github.com/containers/podman-desktop/issues/664

closing as duplicate of https://github.com/containers/podman-desktop/issues/664

**Closed as not planned by benoitf** 2023-01-11 08:13 UTC
