### ISSUE TITLE
Improve Log files management of podman desktop on Mac OS as log with stdout(err) grows a lot in time

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9577] opened 2024-10-24 09:04 UTC
### Is your enhancement related to a problem? Please describe

When running repeatedly some e2e tests on our CI, in some time, I can see that the Podman Desktop Logs grows a lot. We are speaking about x GB of space being consumed to store the logs. Only way - afaik - is to manually remove the log files.

```
pwd
/Users/podmanqe/Library/Logs/Podman Desktop
podmanqe@dev-platform-mac5 Podman Desktop % ls -al  
total 29609696
drwxr--r--   4 podmanqe  staff          128 Jan  9  2024 .
drwx------+ 10 podmanqe  staff          320 Mar 26  2024 ..
-rw-r--r--   1 podmanqe  staff  13222939079 Oct 24 08:11 launchd-stderr.log
-rw-r--r--   1 podmanqe  staff   1928841649 Oct 24 08:11 launchd-stdout.log
```

### Describe the solution you'd like

I am not sure about the solution here, tbh! I am thinking if we can distinguish between version and remove older logs then. Or remove the logs after update. Or there might be a settings that can remove logs older than x days (months). This would require to introduce some log file management system, ie. create logs on dialy base, or when some size of the file is reached.

**Comment by slemeur** [comment] 2024-12-10 10:30
Duplicate of https://github.com/podman-desktop/podman-desktop/issues/10120

**Closed as completed by slemeur** 2024-12-10 10:30 UTC
Labels: os/macOS 🍎
