### ISSUE TITLE
Pop up window on images page broken

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#5238] opened 2023-12-12 22:47 UTC
### Bug description

When trying to select anything from the context menu next to image on images page, the pop-up is broken:
![image](https://github.com/containers/podman-desktop/assets/75624842/84bd0ee1-04b4-4635-b439-cb758a363596)

![image](https://github.com/containers/podman-desktop/assets/75624842/20156ebe-4da1-4609-9535-bbd4d47fa45a)

### Operating system

Fedora 38

### Installation Method

Other

### Version

1.6.0

### Steps to reproduce

Open Images page
Pull an image
Try to open context menu next to pulled image
assert: context pop-up opens
actual: broken cropped version with only part clickable opens

**Comment by deboer-tim** [comment] 2023-12-12 23:00
Fixed in post-1.6 (#5222) and 1.6.1 streams (#5234).

**Comment by odockal** [comment] 2023-12-12 23:23
Dupe of #5220.

**Closed as completed by odockal** 2023-12-12 23:23 UTC
