### ISSUE TITLE
podman says it needs to init but then get VM already exists

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#756] opened 2022-11-03 07:43 UTC
### Bug description

installed podman desktop.
started it and it said it needed to init.
I clicked the button and moved over to settings to browse while waiting.

Exit settings - and now it still tells me it needs to init.

I click init but get:

![2022-11-03_08-41-34](https://user-images.githubusercontent.com/54129/199668836-f185a674-eae7-48b2-acc5-5bfb4e1fec68.png)

version: it says 4.3.0 on the first screen but in about its 0.9.1 which is not a possible choice in the version dropdown 

### Operating system

macos monterey  - apple M1 Max

### Version

0.9.0

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Additional context

.

**Comment by slemeur** [comment] 2022-11-03 07:47
Thanks for the report @maxandersen.
When you go to the settings, are you able to see the machine? 

<img width="1136" alt="Capture d’écran 2022-11-03 à 08 45 49" src="https://user-images.githubusercontent.com/1636769/199669627-41f95416-e5da-4823-8c44-2d46c7052c18.png">


Also, do you have a version of podman previously installed?

**Comment by maxandersen** [comment] 2022-11-03 08:00
This is a brand new fresh machine. no previous podmans have touched it :)

And no, I don't see any "podman machine" in settings:

![2022-11-03_08-59-56](https://user-images.githubusercontent.com/54129/199671410-a85c7d80-72bf-4825-9158-3047a599a893.png)

**Comment by maxandersen** [comment] 2022-11-03 08:27
note, I can run podman and start containers via the ui

**Comment by benoitf** [comment] 2022-11-03 08:48
closing as duplicate of https://github.com/containers/podman-desktop/issues/472

**Closed as not planned by benoitf** 2022-11-03 08:48 UTC
Labels: area/install 🎁, area/settings ⚙️
