### ISSUE TITLE
Pulling short names should be consistent between Podman CLI and Pull Image form

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#8817] opened 2024-09-05 17:44 UTC
### Bug description

If I pull a short name from the command line, I get:
```
% podman pull fedora
Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:latest...
```
but if I go to Images > Pull Image and type in `fedora`, I get `docker.io/library/fedora`.

I'm not sure where it is lost in translation, but we should pull the same image in these cases.

### Operating system

macOS 14.5

### Version

next (development version)

**Comment by SoniaSandler** [comment] 2024-09-24 17:44
@deboer-tim after investigating a bit, I found out that `Dockerode.pull` gets the short name, so the problem is not in the UI. However, even though `Dockerode.pull` uses the short name, it looks like it still pulls the `docker.io` image.
IIUC, `dockerode` uses the local podman machine (if it is the provider that passed), and the local podman machine should use the `/etc/containers/registries.conf.d/000-shortnames.conf` file to configure the correct image.
One solution could be to somehow access `/etc/containers/registries.conf.d/000-shortnames.conf`, and from there pass the full image name, or it might be something that should be fixed outside PD? I'm also open to other suggestions.

**Comment by jeffmaury** [comment] 2024-09-25 08:52
> @deboer-tim after investigating a bit, I found out that `Dockerode.pull` gets the short name, so the problem is not in the UI. However, even though `Dockerode.pull` uses the short name, it looks like it still pulls the `docker.io` image. IIUC, `dockerode` uses the local podman machine (if it is the provider that passed), and the local podman machine should use the `/etc/containers/registries.conf.d/000-shortnames.conf` file to configure the correct image. One solution could be to somehow access `/etc/containers/registries.conf.d/000-shortnames.conf`, and from there pass the full image name, or it might be something that should be fixed outside PD? I'm also open to other suggestions.

That is on the Podman side and it's related to the Docker compatibility layer: if you `run docker pull fedora` against a Podman machine, then it will pull from docker.io:

```
C:\Users\Jeff>docker pull fedora:40
f7bb57d05c2a: Download complete
eca85b75dc19: Download complete
docker.io/library/fedora:40

```

**Comment by benoitf** [comment] 2024-09-26 19:04
I'm not sure that there is even a good solution here.

Having shortname resolving randomly to different repository is on my side really confusing as depending on some configuration you have unpredictable results.

so I don't see why if I use 'fedora' in Podman Desktop it should try to resolve to `registry.fedoraproject.org/fedora`

I think how podman desktop resolves it today is more predictable and the 'expected default behavior' and it should not try to map the CLI behavior that is error prone.

**Comment by deboer-tim** [comment] 2024-09-26 19:41
OTOH people are going to keep hitting this (e.g. #4324), it's confusing when there's an inconsistency between using podman from the cli and ui, and we retain 'docker behaviour' even for people who don't have it installed.

Maybe there's something we could do to at least trigger some understanding of the current behaviour? Like a 'Not what you expected? Click here to learn about Docker compatibility' that linked to an appropriate doc?

**Comment by benoitf** [comment] 2024-09-26 21:12
to me it's the podman CLI that is confusing, it's the only tool where the experience is different than in any other tool.

**Comment by SoniaSandler** [comment] 2024-09-26 21:18
Maybe we could add a small warning text in the area of the image name that all shortname images are pulled from docker hub or if someone inputs a shortname and clicks enter or the pull image button, a message box opens with the warning and it has two buttons, cancel or continue

**Comment by benoitf** [comment] 2024-09-26 21:21
yes as you and Tim suggested, contextual help should improve the user experience

**Comment by jeffmaury** [comment] 2024-09-27 14:22
From my POV the proposed solution is confusing because if users have configured Podman to handle short names (for example enterprise users may want to contact their registry first) then the message will be confusing. Just 1cent

**Comment by SoniaSandler** [comment] 2024-09-27 15:09
@jeffmaury the way that it works now, if you try to pull a shortname image from PD, it won't use the Podman short name config, but the Docker one (unless you change it manually in `containers.conf`), so IIUC, in your scenario, enterprise users won't be able to pull their images using their podman shortnames config, so this message will warn them about this behavior.
I'm working rn on using the `/libpod/images/${shortname}/resolve` endpoint to give the user an option to use the podman config or stay with the default (docker hub), when pulling a shortname image.

**Closed as completed** 2024-10-10 17:05 UTC
