### ISSUE TITLE
Mechanism to change WSL dns when vpn enabled

### ISSUE THREAD

**Issue by TheWurst** [containers/podman-desktop#401] opened 2022-08-12 02:41 UTC
### Is your feature request related to a problem? Please describe

DNS resolution error when pulling images with vpn enabled.

My company requires and enforces a VPN on company hardware.  The /etc/resolv.conf in the Podman machine vm that is created by Podman Desktop is initialized with the dns of the host and not the VPN.  Tom Sweeny had a great post about getting Podman up and running in WSL and following his post i was able to edit the /etc/resolv.conf nameserver in WSL with the dns of the vpn.  

I know this may be an edge case, but it would be tremendously helpful to have an option in podman desktop to set the nameserver in the /etc/resolv.conf of the podman machine.

### Describe the solution you'd like

An option to update /etc/resolv.conf from Preferences->Resources->Podman->Podman Machine

### Additional context

Many thanks to the Podman Desktop team.  Some of the devs in my team have a hard time with containers (that .net life) and a GUI interface will help me to help them see the light.

**Comment by gbraad** [comment] 2022-08-16 12:13
Will also see what we can do from the Podman Machine side

However, the problem is that containers/VM would need to be restarted, as running containers have `resolv.conf` and `environment variables` set as part of the start parameters.

**Comment by benoitf** [comment] 2022-08-16 16:05
created upstream issue: https://github.com/containers/podman/issues/15344

**Comment by cazzoo** [comment] 2022-09-12 21:30
This Is really needed as an option for docker-desktop replacement. Same here, company requires VPN to be activated all the day long... 
Some other alternative found way to overcome this but I let you check what was put in place (rancher-desktop) because I don't know how similar / different their implementation is compared to podman-desktop.

**Comment by darkmastermindz** [comment] 2022-12-11 23:42
Also looking for easier integration support with zscaler dns proxy (requires openssl CA cert configs see: https://forums.balena.io/t/how-to-how-install-balena-cli-in-wsl2-if-behind-proxy-like-zscaler/350969 for example) that is under corporate cisco vpn as well.

**Comment by vietk** [comment] 2023-08-23 11:33
Hello,
I came across this issue while investigating DNS issues in podman desktop.
I think it is also linked to #3577 and can be closed once the PR is merged. The [upstream issue](https://github.com/containers/podman/issues/15344) is closed with the same solution has proposed in the PR.

Regards

**Comment by benoitf** [comment] 2024-02-07 21:13
closing as with user network mode when creating a podman machine on Windows, it's working as expected

**Closed as completed by benoitf** 2024-02-07 21:13 UTC
