### ISSUE TITLE
JavaScript error: write EPIPE

### ISSUE THREAD

**Issue by mydeveloperplanet** [containers/podman-desktop#3445] opened 2023-08-06 09:04 UTC
### Bug description

When I play a Kubernetes YAML file (or when creating a container with a volume mount), a JavaScript error occurs.

The YAML file seems to be imported correctly, the pod and containers are created and work properly. So, it does not seem to be destructive.

### Operating system

Ubuntu 22.04

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

Select the following file: https://github.com/mydeveloperplanet/mypodmanplanet/blob/master/kubernetes/hello-pod-2-with-env.yaml

After clicking the Play-button the error occurs. I cannot copy the contents of the error window, therefore I add this screenshot.
![podman-desktop-kube-error-message](https://github.com/containers/podman-desktop/assets/33178014/ec0876f2-f9cf-4c0d-a241-486acf9df8f0)

### Relevant log output

```shell
None
```

**Comment by benoitf** [comment] 2023-08-06 11:55
hello @mydeveloperplanet thanks for reaching us

If you click on the light bulb 💡 in the bottom right. There is a 'log section's there do you see some errors as well ?


Could you report your podman version as well
Because in Ubuntu by default it's a very old podman version ,(3.4)

**Comment by mydeveloperplanet** [comment] 2023-08-06 12:21
Hi, I am using podman 3.4.4

But, I cannot reproduce the error anymore. I had to restart Podman because deleting a Pod did not finish (spinning wheel continued all the time). After that, everything seems to work just fine.

The logs do not show any errors, but it is good to know that extra information can be found here.

The issue can be closed concerning to me, I cannot provide any extra information for now until I am able to reproduce the error.

**Comment by benoitf** [comment] 2023-08-07 13:22
closing as user can not reproduce anymore. Could reopen if it happens again.
I suspect the version of Podman is also a bit too old

**Closed as not planned by benoitf** 2023-08-07 13:22 UTC

**Comment by mydeveloperplanet** [comment] 2023-08-12 11:26
Hi, I reproduced the error. It starts when I run the following command from the root of this repository: https://github.com/mydeveloperplanet/mypodmanplanet 

`podman run -p 8080:8082 --volume ./properties/application.properties:/opt/app/application.properties:ro --name mypodmanplanet docker.io/mydeveloperplanet/mypodmanplanet:0.0.1-SNAPSHOT`
