### ISSUE TITLE
Some palette commands fail with `Unknown comman command.id}`

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#5888] opened 2024-02-07 06:16 UTC
### Bug description

Commands executed from Palette fails with error
* `Kind: Install ...` 
* `Compose: Checks ...`
* `Compose: Install ...`
* `Kind: Move Image to Cluster ...`
* `Kubectl: Checks ...`
* `Kubectl: Install ...`
* `Lima: Move Image to Cluster ...`

### Operating system

macOS Sonoma 14.3

### Installation Method

Installer from website/GitHub releases

### Version

1.7.0

### Steps to reproduce

1. Show Developer Tools Window
2. Request Command Palette
3. Select `Kind: Install ...` form list
4. Error reported in console

### Relevant log output

```shell
CommandPalette.svelte:130 error executing command Error: Unknown command: kind.install
executeCommand @ CommandPalette.svelte:130
await in executeCommand (async)
clickOnItem @ CommandPalette.svelte:150
click_handler @ CommandPalette.svelte:186
click_handler @ CommandPalette.svelte:192
```
```


### Additional context

_No response_

**Comment by benoitf** [comment] 2024-02-07 08:54
duplicate of https://github.com/containers/podman-desktop/issues/5148

**Closed as not planned by benoitf** 2024-02-07 08:54 UTC
Labels: status/need-triage
