### ISSUE TITLE
Podman Desktop sometimes doesn't detect Kind path

### ISSUE THREAD

**Issue by SoniaSandler** [containers/podman-desktop#9448] opened 2024-10-17 15:05 UTC
### Bug description

Most times, when going to the `CLI Tools` page in `Preferences`, the Kind card shows just the (correct) version of Kind but not the path, and the action buttons on the left are not shown. Also, when trying to start a new Kind cluster, it shows an error saying, `Error: Unable to create kind cluster. No kind cli detected`.

The same also happened with Kubectl once.
1st time:

![Image](https://github.com/user-attachments/assets/2aaa1f07-7fea-487f-baf6-e5b6c2f0ed0c)
![Image](https://github.com/user-attachments/assets/43e68b2b-34ec-43a4-b7d9-d57f935f3547)

2nd time:

![Image](https://github.com/user-attachments/assets/409ab1c3-5914-496a-98ca-54cd8edd84de)

3rd time:
![Image](https://github.com/user-attachments/assets/45ed89f1-8598-429d-b586-63cef91f9279)

### Operating system

Fedora 40

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by amaddio** [comment] 2024-11-12 16:00
Any updates on this? Unfortunately the path to kind is never set in the Podman Desktop app. I am using zshell as default shell on my Mac OS 15.0. The binary is added to the shell env via `~/.zshrc`. Kind is found whenever I start a login shell. Any suggestions to fix this?

**Comment by benoitf** [comment] 2024-11-12 16:05
on macOS, by default, all applications are not inheriting any shell values. (or custom PATH)

**Comment by feloy** [comment] 2024-11-13 14:51
Closing, as the problem is reproducible in older branch but not in main

**Closed as completed by feloy** 2024-11-13 14:51 UTC
Labels: area/extension/kind 🍾

**Comment by dacarab** [comment] 2024-11-17 11:22
I have come across this after installing Podman Desktop yesterday (17/11/2024) on Fedora 41 via Flathub - so I guess this bug is present on the version currently packaged there (reporting as 1.14.1 in the GUI).
