### ISSUE TITLE
Stabilize the registries e2e test scenarios on Mac OS

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#8954] opened 2024-09-18 13:32 UTC
### Is your enhancement related to a problem? Please describe

There are failing test scenarios for registries: `tests/playwright/src/specs/registry-image.spec.ts` and `tests/playwright/src/specs/registry.spec.ts` on mac OS platform on our internal CI.

### Describe the solution you'd like

Please investigate and fix the root cause for the failure on the particular CI on Mac OS.

**Comment by cbr7** [comment] 2024-11-18 09:21
This has been investigated and the issue is that the openshift cicd pipeline used is missing, I've created issue https://github.com/podman-desktop/e2e/issues/275 to track the fix for this.

**Closed as completed** 2024-11-18 09:21 UTC
Labels: os/macOS 🍎, area/tests 🚦
